<?xml version="1.0" encoding="utf-8"?><Database Name="vniim" Class="SqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name_kogo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name_komu" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name_kem" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fio" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="other" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Executors" Member="Executors">
    <Type Name="Executor">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="post" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fio" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Nucleides" Member="Nucleides">
    <Type Name="Nucleide">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="halfPeriod" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Sources" Member="Sources">
    <Type Name="Source">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="orderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nucleideId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="number" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="passport" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rank" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="madeYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="extensionPeriod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="baseValueDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="baseValue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="measValue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="measDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="docNumber" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="isSvid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="oldCustomerName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="actNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="docDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="beginDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="other" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="executors" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Requests" Member="Requests">
    <Type Name="Request">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="incomingNum" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="incomingDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="other" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RequestTrips" Member="RequestTrips">
    <Type Name="RequestTrip">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="days" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="destination" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="other" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RequestItems" Member="RequestItems">
    <Type Name="RequestItem">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="requestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="workTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="deviceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="count" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="other" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WorkTypes" Member="WorkTypes">
    <Type Name="WorkType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Devices" Member="Devices">
    <Type Name="Device">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="reestr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Prices" Member="Prices">
    <Type Name="Price">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="workTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="deviceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fromCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="toCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pricePerItem" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Ranks" Member="Ranks">
    <Type Name="Rank">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="scheme" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="rankv" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>