<?xml version="1.0" encoding="utf-8"?><Database Name="vniim" Class="SqlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ANDREW-ПК\SQLEXPRESS;Initial Catalog=vniim;Integrated Security=True" SettingsObjectName="SourceProlongation.Properties.Settings" SettingsPropertyName="vniimConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name_kogo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name_komu" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="name_kem" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="fio" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="other" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Order">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="customerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="oldCustomerName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="statusId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="actNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="docDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="beginDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="other" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>